---
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install mysql-server
  become: yes
  apt: pkg=mysql-server state=latest

- name: Install python module
  apt:
     name: python3-mysqldb

- name: create mysql database
  mysql_db: name={{ db_name }} state=present

- name: create mysql user
mysql_user: name={{ user_name }} host=localhost password={{ password }} priv={{ db_name }}.*:ALL,GRANT state=present

# - name: ユーザ追加
#   mysql_user: root 
#   mysql_user : "{{ user_name }}"
#   password: "{{ password }}"
#   priv: '{{ db_name }}.*:ALL'
#   state: present

# - name: DB作成
#   mysql_db:
#     login_user: "{{ user_name }}"
#     login_password: "{{ password }}"
#     name: "{{ db_name }}"
#     state: present
#     encoding: utf8mb4

- name: Install php-mysqli
  become: yes
  apt: pkg=php-mysqli state=latest



# - name: Change default nginx site
#   become: yes
#   template: src=default dest=/etc/nginx/sites-available/default
#   notify: restart nginx